# Generated by Django 3.1.7 on 2021-05-17 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/<django.db.models.fields.UUIDField>')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/<django.db.models.fields.UUIDField>')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='is_commentable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_vote_retractable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='max_choice_can_vote',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='poll',
            name='min_choice_can_vote',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.poll', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='poll',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='poll.file'),
        ),
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='poll.image'),
        ),
    ]
