# Generated by Django 3.1.7 on 2021-05-18 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210517_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.poll'),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='selected',
        ),
        migrations.AddField(
            model_name='vote',
            name='selected',
            field=models.ManyToManyField(related_name='votes', to='poll.Choice'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('poll', 'order')},
        ),
        migrations.AddIndex(
            model_name='choice',
            index=models.Index(fields=['poll', 'order'], name='poll_choice_poll_id_00746b_idx'),
        ),
    ]
