# Generated by Django 3.1.7 on 2021-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20210507_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_commentable',
            field=models.BooleanField(default=True),
        ),
    ]
