# Generated by Django 3.1.7 on 2021-05-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20210518_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='visibility_status',
            field=models.CharField(choices=[('VI', 'visible'), ('VA', 'visible_after_vote'), ('HI', 'hidden')], default='VA', max_length=2),
        ),
    ]
