# Generated by Django 3.1.7 on 2021-05-21 12:24

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210520_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='link',
            new_name='attached_http_link',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='polls/files/%Y/%m/%d/<django.db.models.fields.UUIDField>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polls/images/%Y/%m/%d/<django.db.models.fields.UUIDField>'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='max_choice_can_vote',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='poll',
            name='min_choice_can_vote',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
