# Generated by Django 3.1.7 on 2021-05-26 20:06

from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20210526_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=poll.models.File.get_upload_file_url, validators=[poll.models.File.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=poll.models.Image.get_upload_file_url, validators=[poll.models.Image.validate_image_size]),
        ),
    ]
