# Generated by Django 3.1.7 on 2021-05-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_auto_20210527_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name_plural': 'Categories'},
        ),
    ]
