# Generated by Django 3.1.7 on 2021-04-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_auto_20210415_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=48, null=True, upload_to='profiles/images', verbose_name='Avatar', width_field=48),
        ),
    ]
