# Generated by Django 3.1.7 on 2021-04-16 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import socialmedia.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialmedia', '0003_auto_20210415_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrelationship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='socialmedia.userprofile', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='followrelationship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='socialmedia.userprofile', verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=socialmedia.models.UserProfile.uploadAvatar, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
