# Generated by Django 3.1.7 on 2021-05-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_auto_20210506_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',), 'verbose_name': 'User'},
        ),
    ]
