# Generated by Django 3.1.7 on 2021-06-03 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_auto_20210525_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocker_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
