# Generated by Django 3.2 on 2021-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoNarm', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('c', 'Chakerim'), ('m', 'Mokhlesim'), ('n', 'nokarim')], max_length=1),
        ),
    ]
